source 'http://rubygems.org'
ruby '2.3.0'

gem 'cucumber'
gem 'cucumber-core'
gem 'rest-client'
gem 'rake'
gem 'json'
gem 'activesupport'
gem 'httparty'
gem 'nokogiri'
gem 'awesome_print'
gem 'geocoder'
gem 'require_all'
gem 'awesome_print'
gem 'rspec'
gem 'pry'
gem 'fileutils'
gem 'report_builder'
gem 'parallel_tests'
gem 'multi_json'
gem 'httpclient'

